export const ERROR_CODES = {
    NOT_FOUND: 404,
    UNAUTHORIZED: 401,
    BAD_REQUEST: 400,
    INTERNAL_SERVER_ERROR: 500,
}
export const PRISMA_ERROR_CODES = {
    UNIQUE_CONSTRAINT_VIOLATION: 'P2002',
    RECORD_NOT_FOUND: 'P2025',
}