import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import Providers from "@/contexts";
import { HydrationBoundary, QueryClient, dehydrate } from "@tanstack/react-query";
import { getCurrentUser } from "@/api/user";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const messages = await getMessages();

  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryFn: async () => getCurrentUser({
      headers: {
        Cookie: cookies().toString(),
      }
    }),
    queryKey: ['current-user'],
  })

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <HydrationBoundary state={dehydrate(queryClient)}>
              <Navbar />
              {children}
            </HydrationBoundary>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
